import { Component, Input, Inject, forwardRef, AfterViewInit, ElementRef } from "@angular/core";
import { BooleanViews } from "./lcw-grid.column-info";
import { LcwGridComponent } from "./lcw-grid.component";

const selector = 'lcw-grid-auto-generated-column';

@Component({
    moduleId: module.id,
    selector: selector,
    template: "<ng-content></ng-content>",

})
export class LcwGridAutoGeneratedColumnComponent implements AfterViewInit {    
    @Input() format: string;
    @Input() conversions: string;
    @Input() isHidden: boolean = false;
    @Input() isEditable: boolean = false;
    @Input() booleanView: BooleanViews = BooleanViews.checkBox;
    @Input() headerStyle: string = null;

    constructor(
        @Inject(forwardRef(() => LcwGridComponent)) private _parent: LcwGridComponent,
        private _elementRef: ElementRef,
    ) { }

    ngAfterViewInit() {
        if (this._parent.autoGeneratedColumnsParams)
            throw Error(`<${selector}> cannot be used multiple times`);

        const styl = this._elementRef.nativeElement.attributes["style"];
        const valueStyle = styl == null ? null : styl.value;

        const prm: AutoGeneratedColumnsParamters = {};
        if (this.format)
            prm.format = this.format;

        if (this.conversions)
            prm.conversions = this.conversions;

        if (this.isHidden)
            prm.isHidden = this.isHidden;

        if (this.isEditable)
            prm.isEditable = this.isEditable;

        if (this.booleanView)
            prm.booleanView = this.booleanView;

        if (this.headerStyle)
            prm.headerStyle = this.headerStyle;

        if (valueStyle != null)
            prm.valueStyle = valueStyle;

        this._parent.autoGeneratedColumnsParams = prm;
    }
}

export interface AutoGeneratedColumnsParamters {
    format?: string;
    conversions?: string;
    isHidden?: boolean;
    isEditable?: boolean;
    booleanView?: BooleanViews;
    headerStyle?: string;
    valueStyle?: string;
}