//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByRowRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.SaveLocalesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByTableRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLocalesByRowRequest", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.DataLocalizer")]
    [System.SerializableAttribute()]
    public partial class GetLocalesByRowRequest : Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] languagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int objectRefField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                if ((object.ReferenceEquals(this.guidField, value) != true)) {
                    this.guidField = value;
                    this.RaisePropertyChanged("guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] languages {
            get {
                return this.languagesField;
            }
            set {
                if ((object.ReferenceEquals(this.languagesField, value) != true)) {
                    this.languagesField = value;
                    this.RaisePropertyChanged("languages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int objectRef {
            get {
                return this.objectRefField;
            }
            set {
                if ((this.objectRefField.Equals(value) != true)) {
                    this.objectRefField = value;
                    this.RaisePropertyChanged("objectRef");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveLocalesRequest", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.DataLocalizer")]
    [System.SerializableAttribute()]
    public partial class SaveLocalesRequest : Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.DataLocalization valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.DataLocalization value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLocalesByTableRequest", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.DataLocalizer")]
    [System.SerializableAttribute()]
    public partial class GetLocalesByTableRequest : Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] languagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.DataLocalization valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] languages {
            get {
                return this.languagesField;
            }
            set {
                if ((object.ReferenceEquals(this.languagesField, value) != true)) {
                    this.languagesField = value;
                    this.RaisePropertyChanged("languages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.DataLocalization value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataLocalization", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Domain")]
    [System.SerializableAttribute()]
    public partial class DataLocalization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string columnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string databaseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.DataTable localeTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serverNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string columnName {
            get {
                return this.columnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.columnNameField, value) != true)) {
                    this.columnNameField = value;
                    this.RaisePropertyChanged("columnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string databaseName {
            get {
                return this.databaseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.databaseNameField, value) != true)) {
                    this.databaseNameField = value;
                    this.RaisePropertyChanged("databaseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.DataTable localeTable {
            get {
                return this.localeTableField;
            }
            set {
                if ((object.ReferenceEquals(this.localeTableField, value) != true)) {
                    this.localeTableField = value;
                    this.RaisePropertyChanged("localeTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serverName {
            get {
                return this.serverNameField;
            }
            set {
                if ((object.ReferenceEquals(this.serverNameField, value) != true)) {
                    this.serverNameField = value;
                    this.RaisePropertyChanged("serverName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tableName {
            get {
                return this.tableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.tableNameField, value) != true)) {
                    this.tableNameField = value;
                    this.RaisePropertyChanged("tableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataTable", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Domain")]
    [System.SerializableAttribute()]
    public partial class DataTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.Column[] columnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.Row[] rowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.Column[] columns {
            get {
                return this.columnsField;
            }
            set {
                if ((object.ReferenceEquals(this.columnsField, value) != true)) {
                    this.columnsField = value;
                    this.RaisePropertyChanged("columns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                if ((this.pageNumberField.Equals(value) != true)) {
                    this.pageNumberField = value;
                    this.RaisePropertyChanged("pageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.Row[] rows {
            get {
                return this.rowsField;
            }
            set {
                if ((object.ReferenceEquals(this.rowsField, value) != true)) {
                    this.rowsField = value;
                    this.RaisePropertyChanged("rows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalCount {
            get {
                return this.totalCountField;
            }
            set {
                if ((this.totalCountField.Equals(value) != true)) {
                    this.totalCountField = value;
                    this.RaisePropertyChanged("totalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Column", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Domain")]
    [System.SerializableAttribute()]
    public partial class Column : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Row", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Domain")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.RequestBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.ResponseBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.DataLocalization))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.DataTable))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.Column[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.Column))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.Row[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByTableRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByTableResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByRowRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByRowResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.SaveLocalesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.SaveLocalesResponse))]
    public partial class Row : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] valuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isUpdated {
            get {
                return this.isUpdatedField;
            }
            set {
                if ((this.isUpdatedField.Equals(value) != true)) {
                    this.isUpdatedField = value;
                    this.RaisePropertyChanged("isUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] values {
            get {
                return this.valuesField;
            }
            set {
                if ((object.ReferenceEquals(this.valuesField, value) != true)) {
                    this.valuesField = value;
                    this.RaisePropertyChanged("values");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByTableResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByRowResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.SaveLocalesResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] errorMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] warningMessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] errorMessages {
            get {
                return this.errorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.errorMessagesField, value) != true)) {
                    this.errorMessagesField = value;
                    this.RaisePropertyChanged("errorMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] warningMessages {
            get {
                return this.warningMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.warningMessagesField, value) != true)) {
                    this.warningMessagesField = value;
                    this.RaisePropertyChanged("warningMessages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLocalesByTableResponse", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.DataLocalizer")]
    [System.SerializableAttribute()]
    public partial class GetLocalesByTableResponse : Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.DataLocalization valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.DataLocalization value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLocalesByRowResponse", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.DataLocalizer")]
    [System.SerializableAttribute()]
    public partial class GetLocalesByRowResponse : Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.DataLocalization valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.DataLocalization value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveLocalesResponse", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.DataLocalizer")]
    [System.SerializableAttribute()]
    public partial class SaveLocalesResponse : Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isSuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                if ((this.isSuccessField.Equals(value) != true)) {
                    this.isSuccessField = value;
                    this.RaisePropertyChanged("isSuccess");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataLocalizerSvc.IDataLocalizerService")]
    public interface IDataLocalizerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLocalizerService/GetLocalesByTable", ReplyAction="http://tempuri.org/IDataLocalizerService/GetLocalesByTableResponse")]
        Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByTableResponse GetLocalesByTable(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLocalizerService/GetLocalesByTable", ReplyAction="http://tempuri.org/IDataLocalizerService/GetLocalesByTableResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByTableResponse> GetLocalesByTableAsync(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLocalizerService/GetLocalesByRow", ReplyAction="http://tempuri.org/IDataLocalizerService/GetLocalesByRowResponse")]
        Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByRowResponse GetLocalesByRow(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByRowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLocalizerService/GetLocalesByRow", ReplyAction="http://tempuri.org/IDataLocalizerService/GetLocalesByRowResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByRowResponse> GetLocalesByRowAsync(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByRowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLocalizerService/SaveLocales", ReplyAction="http://tempuri.org/IDataLocalizerService/SaveLocalesResponse")]
        Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.SaveLocalesResponse SaveLocales(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.SaveLocalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLocalizerService/SaveLocales", ReplyAction="http://tempuri.org/IDataLocalizerService/SaveLocalesResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.SaveLocalesResponse> SaveLocalesAsync(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.SaveLocalesRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataLocalizerServiceChannel : Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.IDataLocalizerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataLocalizerServiceClient : System.ServiceModel.ClientBase<Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.IDataLocalizerService>, Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.IDataLocalizerService {
        
        public DataLocalizerServiceClient() {
        }
        
        public DataLocalizerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataLocalizerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataLocalizerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataLocalizerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByTableResponse GetLocalesByTable(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByTableRequest request) {
            return base.Channel.GetLocalesByTable(request);
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByTableResponse> GetLocalesByTableAsync(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByTableRequest request) {
            return base.Channel.GetLocalesByTableAsync(request);
        }
        
        public Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByRowResponse GetLocalesByRow(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByRowRequest request) {
            return base.Channel.GetLocalesByRow(request);
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByRowResponse> GetLocalesByRowAsync(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.GetLocalesByRowRequest request) {
            return base.Channel.GetLocalesByRowAsync(request);
        }
        
        public Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.SaveLocalesResponse SaveLocales(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.SaveLocalesRequest request) {
            return base.Channel.SaveLocales(request);
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.SaveLocalesResponse> SaveLocalesAsync(Pars.Util.Puma.Service.IntegrationTest.DataLocalizerSvc.SaveLocalesRequest request) {
            return base.Channel.SaveLocalesAsync(request);
        }
    }
}
