//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimListRequest", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.AuthManagement")]
    [System.SerializableAttribute()]
    public partial class ClaimListRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchText {
            get {
                return this.SearchTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchTextField, value) != true)) {
                    this.SearchTextField = value;
                    this.RaisePropertyChanged("SearchText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimListResponse", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.AuthManagement")]
    [System.SerializableAttribute()]
    public partial class ClaimListResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.Claim> ClaimsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.Claim> Claims {
            get {
                return this.ClaimsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimsField, value) != true)) {
                    this.ClaimsField = value;
                    this.RaisePropertyChanged("Claims");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Claim", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Domain")]
    [System.SerializableAttribute()]
    public partial class Claim : Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.DomainBaseOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaimRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.EntityState EntityStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LocaleData LocaleDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaimRef {
            get {
                return this.ClaimRefField;
            }
            set {
                if ((this.ClaimRefField.Equals(value) != true)) {
                    this.ClaimRefField = value;
                    this.RaisePropertyChanged("ClaimRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.EntityState EntityState {
            get {
                return this.EntityStateField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityStateField, value) != true)) {
                    this.EntityStateField = value;
                    this.RaisePropertyChanged("EntityState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LocaleData LocaleData {
            get {
                return this.LocaleDataField;
            }
            set {
                if ((object.ReferenceEquals(this.LocaleDataField, value) != true)) {
                    this.LocaleDataField = value;
                    this.RaisePropertyChanged("LocaleData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainBaseOfint", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Domain")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LocaleData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.UserGroupRelation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.Role))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.RoleRelation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.Claim))]
    public partial class DomainBaseOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> HasChangedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> HasChanged {
            get {
                return this.HasChangedField;
            }
            set {
                if ((this.HasChangedField.Equals(value) != true)) {
                    this.HasChangedField = value;
                    this.RaisePropertyChanged("HasChanged");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocaleData", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Domain")]
    [System.SerializableAttribute()]
    public partial class LocaleData : Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.DomainBaseOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocaleRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocaleRef {
            get {
                return this.LocaleRefField;
            }
            set {
                if ((this.LocaleRefField.Equals(value) != true)) {
                    this.LocaleRefField = value;
                    this.RaisePropertyChanged("LocaleRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserGroupRelation", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Domain")]
    [System.SerializableAttribute()]
    public partial class UserGroupRelation : Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.DomainBaseOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.MemberState MemberStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RelationRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserGroupRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ValidFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ValidToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.MemberState MemberState {
            get {
                return this.MemberStateField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberStateField, value) != true)) {
                    this.MemberStateField = value;
                    this.RaisePropertyChanged("MemberState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RelationRef {
            get {
                return this.RelationRefField;
            }
            set {
                if ((this.RelationRefField.Equals(value) != true)) {
                    this.RelationRefField = value;
                    this.RaisePropertyChanged("RelationRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserGroupRef {
            get {
                return this.UserGroupRefField;
            }
            set {
                if ((this.UserGroupRefField.Equals(value) != true)) {
                    this.UserGroupRefField = value;
                    this.RaisePropertyChanged("UserGroupRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidFrom {
            get {
                return this.ValidFromField;
            }
            set {
                if ((this.ValidFromField.Equals(value) != true)) {
                    this.ValidFromField = value;
                    this.RaisePropertyChanged("ValidFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidTo {
            get {
                return this.ValidToField;
            }
            set {
                if ((this.ValidToField.Equals(value) != true)) {
                    this.ValidToField = value;
                    this.RaisePropertyChanged("ValidTo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Domain")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.RoleRelation))]
    public partial class Role : Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.DomainBaseOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> createdDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> createdUserRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.EntityState entityStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LocaleData localeDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> modifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> modifiedUserRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int roleRefField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> createdDate {
            get {
                return this.createdDateField;
            }
            set {
                if ((this.createdDateField.Equals(value) != true)) {
                    this.createdDateField = value;
                    this.RaisePropertyChanged("createdDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> createdUserRef {
            get {
                return this.createdUserRefField;
            }
            set {
                if ((this.createdUserRefField.Equals(value) != true)) {
                    this.createdUserRefField = value;
                    this.RaisePropertyChanged("createdUserRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.EntityState entityState {
            get {
                return this.entityStateField;
            }
            set {
                if ((object.ReferenceEquals(this.entityStateField, value) != true)) {
                    this.entityStateField = value;
                    this.RaisePropertyChanged("entityState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LocaleData localeData {
            get {
                return this.localeDataField;
            }
            set {
                if ((object.ReferenceEquals(this.localeDataField, value) != true)) {
                    this.localeDataField = value;
                    this.RaisePropertyChanged("localeData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> modifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                if ((this.modifiedDateField.Equals(value) != true)) {
                    this.modifiedDateField = value;
                    this.RaisePropertyChanged("modifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> modifiedUserRef {
            get {
                return this.modifiedUserRefField;
            }
            set {
                if ((this.modifiedUserRefField.Equals(value) != true)) {
                    this.modifiedUserRefField = value;
                    this.RaisePropertyChanged("modifiedUserRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int roleRef {
            get {
                return this.roleRefField;
            }
            set {
                if ((this.roleRefField.Equals(value) != true)) {
                    this.roleRefField = value;
                    this.RaisePropertyChanged("roleRef");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleRelation", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Domain")]
    [System.SerializableAttribute()]
    public partial class RoleRelation : Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.Role {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RelatedRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.MemberState memberStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int relationRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime validFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime validToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RelatedRef {
            get {
                return this.RelatedRefField;
            }
            set {
                if ((this.RelatedRefField.Equals(value) != true)) {
                    this.RelatedRefField = value;
                    this.RaisePropertyChanged("RelatedRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.MemberState memberState {
            get {
                return this.memberStateField;
            }
            set {
                if ((object.ReferenceEquals(this.memberStateField, value) != true)) {
                    this.memberStateField = value;
                    this.RaisePropertyChanged("memberState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int relationRef {
            get {
                return this.relationRefField;
            }
            set {
                if ((this.relationRefField.Equals(value) != true)) {
                    this.relationRefField = value;
                    this.RaisePropertyChanged("relationRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime validFrom {
            get {
                return this.validFromField;
            }
            set {
                if ((this.validFromField.Equals(value) != true)) {
                    this.validFromField = value;
                    this.RaisePropertyChanged("validFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime validTo {
            get {
                return this.validToField;
            }
            set {
                if ((this.validToField.Equals(value) != true)) {
                    this.validToField = value;
                    this.RaisePropertyChanged("validTo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityState", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Domain")]
    [System.SerializableAttribute()]
    public partial class EntityState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EntityStateRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short EntityStateRef {
            get {
                return this.EntityStateRefField;
            }
            set {
                if ((this.EntityStateRefField.Equals(value) != true)) {
                    this.EntityStateRefField = value;
                    this.RaisePropertyChanged("EntityStateRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberState", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Domain")]
    [System.SerializableAttribute()]
    public partial class MemberState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short MemberStateRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short MemberStateRef {
            get {
                return this.MemberStateRefField;
            }
            set {
                if ((this.MemberStateRefField.Equals(value) != true)) {
                    this.MemberStateRefField = value;
                    this.RaisePropertyChanged("MemberStateRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserGroupRelationRequest", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.AuthManagement")]
    [System.SerializableAttribute()]
    public partial class UserGroupRelationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaimRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaimRef {
            get {
                return this.ClaimRefField;
            }
            set {
                if ((this.ClaimRefField.Equals(value) != true)) {
                    this.ClaimRefField = value;
                    this.RaisePropertyChanged("ClaimRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserGroupRelationResponse", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.AuthManagement")]
    [System.SerializableAttribute()]
    public partial class UserGroupRelationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.UserGroupRelation> UserGroupsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.UserGroupRelation> UserGroups {
            get {
                return this.UserGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGroupsField, value) != true)) {
                    this.UserGroupsField = value;
                    this.RaisePropertyChanged("UserGroups");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimSaveRequest", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.AuthManagement")]
    [System.SerializableAttribute()]
    public partial class ClaimSaveRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.Claim ClaimField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.Claim Claim {
            get {
                return this.ClaimField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimField, value) != true)) {
                    this.ClaimField = value;
                    this.RaisePropertyChanged("Claim");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimSaveResponse", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.AuthManagement")]
    [System.SerializableAttribute()]
    public partial class ClaimSaveResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.Claim ClaimField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.Claim Claim {
            get {
                return this.ClaimField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimField, value) != true)) {
                    this.ClaimField = value;
                    this.RaisePropertyChanged("Claim");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.SaveRoleRelationRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByStartingNameRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByContainingNameRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByClaimRefRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveRoleRelationRequest", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.AuthManagement")]
    [System.SerializableAttribute()]
    public partial class SaveRoleRelationRequest : Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.RoleRelation RoleRelationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.RoleRelation RoleRelation {
            get {
                return this.RoleRelationField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleRelationField, value) != true)) {
                    this.RoleRelationField = value;
                    this.RaisePropertyChanged("RoleRelation");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRolesByStartingNameRequest", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.AuthManagement")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByContainingNameRequest))]
    public partial class GetRolesByStartingNameRequest : Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string searchTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string searchText {
            get {
                return this.searchTextField;
            }
            set {
                if ((object.ReferenceEquals(this.searchTextField, value) != true)) {
                    this.searchTextField = value;
                    this.RaisePropertyChanged("searchText");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRolesByContainingNameRequest", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.AuthManagement")]
    [System.SerializableAttribute()]
    public partial class GetRolesByContainingNameRequest : Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByStartingNameRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRolesByClaimRefRequest", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.AuthManagement")]
    [System.SerializableAttribute()]
    public partial class GetRolesByClaimRefRequest : Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string searchTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                if ((this.pageNumberField.Equals(value) != true)) {
                    this.pageNumberField = value;
                    this.RaisePropertyChanged("pageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                if ((this.pageSizeField.Equals(value) != true)) {
                    this.pageSizeField = value;
                    this.RaisePropertyChanged("pageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string searchText {
            get {
                return this.searchTextField;
            }
            set {
                if ((object.ReferenceEquals(this.searchTextField, value) != true)) {
                    this.searchTextField = value;
                    this.RaisePropertyChanged("searchText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.SaveRoleRelationResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LookupResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByClaimRefResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> errorMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> warningMessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> errorMessages {
            get {
                return this.errorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.errorMessagesField, value) != true)) {
                    this.errorMessagesField = value;
                    this.RaisePropertyChanged("errorMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> warningMessages {
            get {
                return this.warningMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.warningMessagesField, value) != true)) {
                    this.warningMessagesField = value;
                    this.RaisePropertyChanged("warningMessages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveRoleRelationResponse", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.AuthManagement")]
    [System.SerializableAttribute()]
    public partial class SaveRoleRelationResponse : Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.RoleRelation ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.RoleRelation Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupResponse", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service")]
    [System.SerializableAttribute()]
    public partial class LookupResponse : Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LookupItem> valuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LookupItem> values {
            get {
                return this.valuesField;
            }
            set {
                if ((object.ReferenceEquals(this.valuesField, value) != true)) {
                    this.valuesField = value;
                    this.RaisePropertyChanged("values");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRolesByClaimRefResponse", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.AuthManagement")]
    [System.SerializableAttribute()]
    public partial class GetRolesByClaimRefResponse : Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int countField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.RoleRelation> valuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int count {
            get {
                return this.countField;
            }
            set {
                if ((this.countField.Equals(value) != true)) {
                    this.countField = value;
                    this.RaisePropertyChanged("count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.RoleRelation> values {
            get {
                return this.valuesField;
            }
            set {
                if ((object.ReferenceEquals(this.valuesField, value) != true)) {
                    this.valuesField = value;
                    this.RaisePropertyChanged("values");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupItem", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Domain")]
    [System.SerializableAttribute()]
    public partial class LookupItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RefField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ref {
            get {
                return this.RefField;
            }
            set {
                if ((this.RefField.Equals(value) != true)) {
                    this.RefField = value;
                    this.RaisePropertyChanged("Ref");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthManagementSvc.IAuthManagementService")]
    public interface IAuthManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthManagementService/GetClaims", ReplyAction="http://tempuri.org/IAuthManagementService/GetClaimsResponse")]
        Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimListResponse GetClaims(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthManagementService/GetClaims", ReplyAction="http://tempuri.org/IAuthManagementService/GetClaimsResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimListResponse> GetClaimsAsync(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthManagementService/GetUserGroupsByClaimRef", ReplyAction="http://tempuri.org/IAuthManagementService/GetUserGroupsByClaimRefResponse")]
        Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.UserGroupRelationResponse GetUserGroupsByClaimRef(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.UserGroupRelationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthManagementService/GetUserGroupsByClaimRef", ReplyAction="http://tempuri.org/IAuthManagementService/GetUserGroupsByClaimRefResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.UserGroupRelationResponse> GetUserGroupsByClaimRefAsync(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.UserGroupRelationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthManagementService/SaveClaim", ReplyAction="http://tempuri.org/IAuthManagementService/SaveClaimResponse")]
        Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimSaveResponse SaveClaim(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimSaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthManagementService/SaveClaim", ReplyAction="http://tempuri.org/IAuthManagementService/SaveClaimResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimSaveResponse> SaveClaimAsync(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimSaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthManagementService/GetRolesByClaimRef", ReplyAction="http://tempuri.org/IAuthManagementService/GetRolesByClaimRefResponse")]
        Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByClaimRefResponse GetRolesByClaimRef(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByClaimRefRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthManagementService/GetRolesByClaimRef", ReplyAction="http://tempuri.org/IAuthManagementService/GetRolesByClaimRefResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByClaimRefResponse> GetRolesByClaimRefAsync(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByClaimRefRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthManagementService/SaveRoleRelation", ReplyAction="http://tempuri.org/IAuthManagementService/SaveRoleRelationResponse")]
        Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.SaveRoleRelationResponse SaveRoleRelation(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.SaveRoleRelationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthManagementService/SaveRoleRelation", ReplyAction="http://tempuri.org/IAuthManagementService/SaveRoleRelationResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.SaveRoleRelationResponse> SaveRoleRelationAsync(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.SaveRoleRelationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthManagementService/GetRolesAsLookupByStartingName", ReplyAction="http://tempuri.org/IAuthManagementService/GetRolesAsLookupByStartingNameResponse")]
        Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LookupResponse GetRolesAsLookupByStartingName(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByStartingNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthManagementService/GetRolesAsLookupByStartingName", ReplyAction="http://tempuri.org/IAuthManagementService/GetRolesAsLookupByStartingNameResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LookupResponse> GetRolesAsLookupByStartingNameAsync(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByStartingNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthManagementService/GetRolesAsLookupByContainingName", ReplyAction="http://tempuri.org/IAuthManagementService/GetRolesAsLookupByContainingNameRespons" +
            "e")]
        Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LookupResponse GetRolesAsLookupByContainingName(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByContainingNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthManagementService/GetRolesAsLookupByContainingName", ReplyAction="http://tempuri.org/IAuthManagementService/GetRolesAsLookupByContainingNameRespons" +
            "e")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LookupResponse> GetRolesAsLookupByContainingNameAsync(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByContainingNameRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthManagementServiceChannel : Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.IAuthManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthManagementServiceClient : System.ServiceModel.ClientBase<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.IAuthManagementService>, Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.IAuthManagementService {
        
        public AuthManagementServiceClient() {
        }
        
        public AuthManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimListResponse GetClaims(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimListRequest request) {
            return base.Channel.GetClaims(request);
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimListResponse> GetClaimsAsync(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimListRequest request) {
            return base.Channel.GetClaimsAsync(request);
        }
        
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.UserGroupRelationResponse GetUserGroupsByClaimRef(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.UserGroupRelationRequest request) {
            return base.Channel.GetUserGroupsByClaimRef(request);
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.UserGroupRelationResponse> GetUserGroupsByClaimRefAsync(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.UserGroupRelationRequest request) {
            return base.Channel.GetUserGroupsByClaimRefAsync(request);
        }
        
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimSaveResponse SaveClaim(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimSaveRequest request) {
            return base.Channel.SaveClaim(request);
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimSaveResponse> SaveClaimAsync(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.ClaimSaveRequest request) {
            return base.Channel.SaveClaimAsync(request);
        }
        
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByClaimRefResponse GetRolesByClaimRef(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByClaimRefRequest request) {
            return base.Channel.GetRolesByClaimRef(request);
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByClaimRefResponse> GetRolesByClaimRefAsync(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByClaimRefRequest request) {
            return base.Channel.GetRolesByClaimRefAsync(request);
        }
        
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.SaveRoleRelationResponse SaveRoleRelation(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.SaveRoleRelationRequest request) {
            return base.Channel.SaveRoleRelation(request);
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.SaveRoleRelationResponse> SaveRoleRelationAsync(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.SaveRoleRelationRequest request) {
            return base.Channel.SaveRoleRelationAsync(request);
        }
        
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LookupResponse GetRolesAsLookupByStartingName(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByStartingNameRequest request) {
            return base.Channel.GetRolesAsLookupByStartingName(request);
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LookupResponse> GetRolesAsLookupByStartingNameAsync(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByStartingNameRequest request) {
            return base.Channel.GetRolesAsLookupByStartingNameAsync(request);
        }
        
        public Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LookupResponse GetRolesAsLookupByContainingName(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByContainingNameRequest request) {
            return base.Channel.GetRolesAsLookupByContainingName(request);
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.LookupResponse> GetRolesAsLookupByContainingNameAsync(Pars.Util.Puma.Service.IntegrationTest.AuthManagementSvc.GetRolesByContainingNameRequest request) {
            return base.Channel.GetRolesAsLookupByContainingNameAsync(request);
        }
    }
}
