//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pars.Util.Puma.UI.Mvc.DefinitionSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEntityStatesResponse", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.Definition")]
    [System.SerializableAttribute()]
    public partial class GetEntityStatesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Domain.EntityState[] EntityStatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Domain.EntityState[] EntityStates {
            get {
                return this.EntityStatesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityStatesField, value) != true)) {
                    this.EntityStatesField = value;
                    this.RaisePropertyChanged("EntityStates");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberStateListResponse", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.Definition")]
    [System.SerializableAttribute()]
    public partial class MemberStateListResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pars.Util.Puma.Domain.MemberState[] MemberStatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pars.Util.Puma.Domain.MemberState[] MemberStates {
            get {
                return this.MemberStatesField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberStatesField, value) != true)) {
                    this.MemberStatesField = value;
                    this.RaisePropertyChanged("MemberStates");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDatabasesRequest", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.Definition")]
    [System.SerializableAttribute()]
    public partial class GetDatabasesRequest : Pars.Util.Puma.Domain.RequestBase, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int serverRefField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int serverRef {
            get {
                return this.serverRefField;
            }
            set {
                if ((this.serverRefField.Equals(value) != true)) {
                    this.serverRefField = value;
                    this.RaisePropertyChanged("serverRef");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTablesRequest", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.Definition")]
    [System.SerializableAttribute()]
    public partial class GetTablesRequest : Pars.Util.Puma.Domain.RequestBase, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int databaseRefField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int databaseRef {
            get {
                return this.databaseRefField;
            }
            set {
                if ((this.databaseRefField.Equals(value) != true)) {
                    this.databaseRefField = value;
                    this.RaisePropertyChanged("databaseRef");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTableColumnsRequest", Namespace="http://schemas.datacontract.org/2004/07/Pars.Util.Puma.Service.Definition")]
    [System.SerializableAttribute()]
    public partial class GetTableColumnsRequest : Pars.Util.Puma.Domain.RequestBase, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tableRefField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tableRef {
            get {
                return this.tableRefField;
            }
            set {
                if ((this.tableRefField.Equals(value) != true)) {
                    this.tableRefField = value;
                    this.RaisePropertyChanged("tableRef");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DefinitionSvc.IDefinitionService")]
    public interface IDefinitionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetEntityStates", ReplyAction="http://tempuri.org/IDefinitionService/GetEntityStatesResponse")]
        Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetEntityStatesResponse GetEntityStates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetEntityStates", ReplyAction="http://tempuri.org/IDefinitionService/GetEntityStatesResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetEntityStatesResponse> GetEntityStatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetMemberStates", ReplyAction="http://tempuri.org/IDefinitionService/GetMemberStatesResponse")]
        Pars.Util.Puma.UI.Mvc.DefinitionSvc.MemberStateListResponse GetMemberStates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetMemberStates", ReplyAction="http://tempuri.org/IDefinitionService/GetMemberStatesResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.UI.Mvc.DefinitionSvc.MemberStateListResponse> GetMemberStatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetSegmentsAsLookup", ReplyAction="http://tempuri.org/IDefinitionService/GetSegmentsAsLookupResponse")]
        Pars.Util.Puma.Domain.LookupResponse GetSegmentsAsLookup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetSegmentsAsLookup", ReplyAction="http://tempuri.org/IDefinitionService/GetSegmentsAsLookupResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetSegmentsAsLookupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetSubSegmentsAsLookup", ReplyAction="http://tempuri.org/IDefinitionService/GetSubSegmentsAsLookupResponse")]
        Pars.Util.Puma.Domain.LookupResponse GetSubSegmentsAsLookup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetSubSegmentsAsLookup", ReplyAction="http://tempuri.org/IDefinitionService/GetSubSegmentsAsLookupResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetSubSegmentsAsLookupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetBusinessLinesAsLookup", ReplyAction="http://tempuri.org/IDefinitionService/GetBusinessLinesAsLookupResponse")]
        Pars.Util.Puma.Domain.LookupResponse GetBusinessLinesAsLookup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetBusinessLinesAsLookup", ReplyAction="http://tempuri.org/IDefinitionService/GetBusinessLinesAsLookupResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetBusinessLinesAsLookupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetAgeSexGroupsAsLookup", ReplyAction="http://tempuri.org/IDefinitionService/GetAgeSexGroupsAsLookupResponse")]
        Pars.Util.Puma.Domain.LookupResponse GetAgeSexGroupsAsLookup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetAgeSexGroupsAsLookup", ReplyAction="http://tempuri.org/IDefinitionService/GetAgeSexGroupsAsLookupResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetAgeSexGroupsAsLookupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetSupplierTypesAsLookup", ReplyAction="http://tempuri.org/IDefinitionService/GetSupplierTypesAsLookupResponse")]
        Pars.Util.Puma.Domain.LookupResponse GetSupplierTypesAsLookup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetSupplierTypesAsLookup", ReplyAction="http://tempuri.org/IDefinitionService/GetSupplierTypesAsLookupResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetSupplierTypesAsLookupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetServers", ReplyAction="http://tempuri.org/IDefinitionService/GetServersResponse")]
        Pars.Util.Puma.Domain.LookupResponse GetServers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetServers", ReplyAction="http://tempuri.org/IDefinitionService/GetServersResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetServersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetDatabases", ReplyAction="http://tempuri.org/IDefinitionService/GetDatabasesResponse")]
        Pars.Util.Puma.Domain.LookupResponse GetDatabases(Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetDatabasesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetDatabases", ReplyAction="http://tempuri.org/IDefinitionService/GetDatabasesResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetDatabasesAsync(Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetDatabasesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetTables", ReplyAction="http://tempuri.org/IDefinitionService/GetTablesResponse")]
        Pars.Util.Puma.Domain.LookupResponse GetTables(Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetTablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetTables", ReplyAction="http://tempuri.org/IDefinitionService/GetTablesResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetTablesAsync(Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetTablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetTableColumns", ReplyAction="http://tempuri.org/IDefinitionService/GetTableColumnsResponse")]
        Pars.Util.Puma.Domain.LookupResponse GetTableColumns(Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetTableColumnsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetTableColumns", ReplyAction="http://tempuri.org/IDefinitionService/GetTableColumnsResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetTableColumnsAsync(Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetTableColumnsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetLanguages", ReplyAction="http://tempuri.org/IDefinitionService/GetLanguagesResponse")]
        Pars.Util.Puma.Domain.LookupResponse GetLanguages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDefinitionService/GetLanguages", ReplyAction="http://tempuri.org/IDefinitionService/GetLanguagesResponse")]
        System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetLanguagesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDefinitionServiceChannel : Pars.Util.Puma.UI.Mvc.DefinitionSvc.IDefinitionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DefinitionServiceClient : System.ServiceModel.ClientBase<Pars.Util.Puma.UI.Mvc.DefinitionSvc.IDefinitionService>, Pars.Util.Puma.UI.Mvc.DefinitionSvc.IDefinitionService {
        
        public DefinitionServiceClient() {
        }
        
        public DefinitionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DefinitionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DefinitionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DefinitionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetEntityStatesResponse GetEntityStates() {
            return base.Channel.GetEntityStates();
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetEntityStatesResponse> GetEntityStatesAsync() {
            return base.Channel.GetEntityStatesAsync();
        }
        
        public Pars.Util.Puma.UI.Mvc.DefinitionSvc.MemberStateListResponse GetMemberStates() {
            return base.Channel.GetMemberStates();
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.UI.Mvc.DefinitionSvc.MemberStateListResponse> GetMemberStatesAsync() {
            return base.Channel.GetMemberStatesAsync();
        }
        
        public Pars.Util.Puma.Domain.LookupResponse GetSegmentsAsLookup() {
            return base.Channel.GetSegmentsAsLookup();
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetSegmentsAsLookupAsync() {
            return base.Channel.GetSegmentsAsLookupAsync();
        }
        
        public Pars.Util.Puma.Domain.LookupResponse GetSubSegmentsAsLookup() {
            return base.Channel.GetSubSegmentsAsLookup();
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetSubSegmentsAsLookupAsync() {
            return base.Channel.GetSubSegmentsAsLookupAsync();
        }
        
        public Pars.Util.Puma.Domain.LookupResponse GetBusinessLinesAsLookup() {
            return base.Channel.GetBusinessLinesAsLookup();
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetBusinessLinesAsLookupAsync() {
            return base.Channel.GetBusinessLinesAsLookupAsync();
        }
        
        public Pars.Util.Puma.Domain.LookupResponse GetAgeSexGroupsAsLookup() {
            return base.Channel.GetAgeSexGroupsAsLookup();
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetAgeSexGroupsAsLookupAsync() {
            return base.Channel.GetAgeSexGroupsAsLookupAsync();
        }
        
        public Pars.Util.Puma.Domain.LookupResponse GetSupplierTypesAsLookup() {
            return base.Channel.GetSupplierTypesAsLookup();
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetSupplierTypesAsLookupAsync() {
            return base.Channel.GetSupplierTypesAsLookupAsync();
        }
        
        public Pars.Util.Puma.Domain.LookupResponse GetServers() {
            return base.Channel.GetServers();
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetServersAsync() {
            return base.Channel.GetServersAsync();
        }
        
        public Pars.Util.Puma.Domain.LookupResponse GetDatabases(Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetDatabasesRequest request) {
            return base.Channel.GetDatabases(request);
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetDatabasesAsync(Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetDatabasesRequest request) {
            return base.Channel.GetDatabasesAsync(request);
        }
        
        public Pars.Util.Puma.Domain.LookupResponse GetTables(Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetTablesRequest request) {
            return base.Channel.GetTables(request);
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetTablesAsync(Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetTablesRequest request) {
            return base.Channel.GetTablesAsync(request);
        }
        
        public Pars.Util.Puma.Domain.LookupResponse GetTableColumns(Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetTableColumnsRequest request) {
            return base.Channel.GetTableColumns(request);
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetTableColumnsAsync(Pars.Util.Puma.UI.Mvc.DefinitionSvc.GetTableColumnsRequest request) {
            return base.Channel.GetTableColumnsAsync(request);
        }
        
        public Pars.Util.Puma.Domain.LookupResponse GetLanguages() {
            return base.Channel.GetLanguages();
        }
        
        public System.Threading.Tasks.Task<Pars.Util.Puma.Domain.LookupResponse> GetLanguagesAsync() {
            return base.Channel.GetLanguagesAsync();
        }
    }
}
